### ISSUE TITLE
KeyError: 'LlavaConfig'

### ISSUE THREAD

**Issue by weny911** [Meituan-AutoML/Lenna#2]
when I run
```
python chat.py --ckpt-path ckpt/Lenna-7B --vis_save_path ./vis_output
```
An exception is thrown
```
Traceback (most recent call last):
  File "/root/Lenna-main/chat.py", line 138, in <module>
    main(sys.argv[1:])
  File "/root/Lenna-main/chat.py", line 30, in main
    tokenizer = AutoTokenizer.from_pretrained(
  File "/root/miniconda3/envs/lenna/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 718, in from_pretrained
    tokenizer_class_py, tokenizer_class_fast = TOKENIZER_MAPPING[type(config)]
  File "/root/miniconda3/envs/lenna/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 663, in __getitem__
    model_type = self._reverse_config_mapping[key.__name__]
KeyError: 'LlavaConfig'
```

**Comment by weifei7** [comment]
sorry，we have met some errors when upload our model to hughingface. The model‘s huggingface url is updated now.  Please reload it，sorry for this

**Comment by weifei7** [comment]
if you still have some questions running Lenns‘s code，plese connect me fwei_mail@163.com，looking forward to help u～ @liwenyang-911

**Comment by weifei7** [comment]
checkpoint download unsuccessfully
